#ifndef LUEFTERHARDWARE_H_INCLUDED
#define LUEFTERHARDWARE_H_INCLUDED

// Lüfter einschalten
#define LUEFTER_ON_PORT PORTD
#define LUEFTER_ON_PIN  PIN4_bm
#define LUEFTER_ON   LUEFTER_ON_PORT.OUTSET=LUEFTER_ON_PIN
#define LUEFTER_OFF  LUEFTER_ON_PORT.OUTCLR=LUEFTER_ON_PIN
//Lüfter PWM
#define LUEFTER_PWM_PORT PORTD
#define LUEFTER_PWM_PIN  PIN3_bm

// Lüfter-Status-Taste (manuell)
#define LUEFTER_TASTE_PORT  PORTD
#define LUEFTER_TASTE_PIN   PIN7_bm

// Klappen-Status-Taste (manuell)
#define KLAPPE_TASTE_PORT   PORTD
#define KLAPPE_TASTE_PIN    PIN6_bm

// Endschalter OPEN
#define KLAPPE_ES_OPEN_PORT PORTA
#define KLAPPE_ES_OPEN_PIN  PIN7_bm

#define KLAPPE_ES_OPEN_DATA			(KLAPPE_ES_OPEN_PORT.IN & KLAPPE_ES_OPEN_PIN)
#define KLAPPE_ES_OPEN_IS_CLEAR	bit_is_clear(KLAPPE_ES_OPEN_PORT,KLAPPE_ES_OPEN_PIN)
#define KLAPPE_ES_OPEN_IS_SET		bit_is_set(KLAPPE_ES_OPEN_PORT,KLAPPE_ES_OPEN_PIN)
#define GET_KLAPPE_ES_OPEN      (KLAPPE_ES_OPEN_DATA_SET==0 ? false: true)

// Endschalter CLOSE
#define KLAPPE_ES_CLOSE_PORT  PORTA
#define KLAPPE_ES_CLOSE_PIN   PIN1_bm

#define KLAPPE_ES_CLOSE_DATA			(KLAPPE_ES_CLOSE_PORT.IN & KLAPPE_ES_CLOSE_PIN)
#define KLAPPE_ES_CLOSE_IS_CLEAR	bit_is_clear(KLAPPE_ES_CLOSE_PORT,KLAPPE_ES_CLOSE_PIN)
#define KLAPPE_ES_CLOSE_IS_SET		bit_is_set(KLAPPE_ES_CLOSE_PORT,KLAPPE_ES_CLOSE_PIN)
#define GET_KLAPPE_ES_CLOSE      (KLAPPE_ES_CLOSE_DATA_SET==0 ? false: true)

// h-Brücke
#define HBRIDGE_MODE1_PORT  PORTC
#define HBRIDGE_MODE1_PIN   PIN4_bm
#define HBRIDGE_MODE2_PORT  PORTC
#define HBRIDGE_MODE2_PIN   PIN2_bm
#define HBRIDGE_PHASE_PORT  PORTC
#define HBRIDGE_PHASE_PIN   PIN5_bm
#define HBRIDGE_NSLEEP_PORT  PORTC
#define HBRIDGE_NSLEEP_PIN   PIN6_bm
#define HBRIDGE_ENABLE_PORT  PORTC
#define HBRIDGE_ENABLE_PIN   PIN7_bm
#define HBRIDGE_NFAULT_PORT  PORTC
#define HBRIDGE_NFAULT_PIN   PIN3_bm
#define HBRIDGE_VPROPI_PORT  PORTA
#define HBRIDGE_VPROPI_PIN   PIN6_bm

#define HBRIDGE_MODE1_SET   HBRIDGE_MODE1_PORT.OUTSET=HBRIDGE_MODE1_PIN
#define HBRIDGE_MODE1_CLR   HBRIDGE_MODE1_PORT.OUTCLR=HBRIDGE_MODE1_PIN
#define HBRIDGE_MODE2_SET   HBRIDGE_MODE2_PORT.OUTSET=HBRIDGE_MODE2_PIN
#define HBRIDGE_MODE2_CLR   HBRIDGE_MODE2_PORT.OUTCLR=HBRIDGE_MODE2_PIN
#define HBRIDGE_WAKEUP      HBRIDGE_NSLEEP_PORT.OUTSET=HBRIDGE_NSLEEP_PIN
#define HBRIDGE_SLEEP       HBRIDGE_NSLEEP_PORT.OUTCLR=HBRIDGE_NSLEEP_PIN
#define HBRIDGE_CLOCKWISE   HBRIDGE_PHASE_PORT.OUTSET=HBRIDGE_PHASE_PIN
#define HBRIDGE_CCLOCKWISE  HBRIDGE_PHASE_PORT.OUTCLR=HBRIDGE_PHASE_PIN
#define HBRIDGE_START       HBRIDGE_ENABLE_PORT.OUTSET=HBRIDGE_ENABLE_PIN
#define HBRIDGE_STOP        HBRIDGE_ENABLE_PORT.OUTCLR=HBRIDGE_ENABLE_PIN

#endif // LUEFTERHARDWARE_H_INCLUDED
